[firebase]
apiKey = "AIzaSyByibx2O0mHRGuB--I2NdSBHF4DkcdLiVI"
authDomain = "mind-in-prediction.firebaseapp.com"
databaseURL = "https://mind-in-prediction-default-rtdb.firebaseio.com"
projectId = "mind-in-prediction"
storageBucket = "mind-in-prediction.firebasestorage.app"
messagingSenderId = "413032670663"
appId = "1:413032670663:web:f3caf7550f611b8504e5e2"
